workflows:
  ios-test:
    name: "iOS Build Test"
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        AZURE_STORAGE_ACCOUNT: "tongiapks"
        AZURE_CONTAINER: "apk"
      groups:
        - azure

    triggering:
      events:
        - push

    scripts:
      - name: Clean
        script: |
          cd frontend
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Flutter pub get
        script: |
          cd frontend
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios
          pod install

      - name: Build iOS archive
        script: |
          cd frontend
          set -e
          flutter build ios --release --no-codesign
          
          echo "✅ Build de iOS completado"
          echo "📦 Verificando archivos generados:"
          ls -lh build/ios/archive/ || true
          ls -lh build/ios/iphoneos/ || true

      - name: Create IPA from xcarchive
        script: |
          cd frontend
          
          # Crear directorio para el IPA
          mkdir -p build/ios/ipa
          
          # Buscar el archivo .app en el xcarchive
          APP_PATH=$(find build/ios/archive -name "Runner.app" | head -n 1)
          
          if [ -z "$APP_PATH" ]; then
            echo "❌ Error: No se encontró Runner.app"
            ls -R build/ios/
            exit 1
          fi
          
          echo "✅ Encontrado: $APP_PATH"
          
          # Crear el IPA manualmente
          PAYLOAD_DIR="build/ios/ipa/Payload"
          mkdir -p "$PAYLOAD_DIR"
          cp -r "$APP_PATH" "$PAYLOAD_DIR/"
          
          cd build/ios/ipa
          zip -r Runner.ipa Payload
          rm -rf Payload
          cd ../../..
          
          echo "✅ IPA creado exitosamente"
          ls -lh build/ios/ipa/

      - name: Install Azure CLI
        script: |
          brew update
          brew install azure-cli

      - name: Upload IPA to Azure Blob Storage
        script: |
          cd frontend
          
          IPA_FILE="build/ios/ipa/Runner.ipa"
          
          if [ ! -f "$IPA_FILE" ]; then
            echo "❌ Error: No se encontró el archivo IPA en $IPA_FILE"
            ls -R build/ios/
            exit 1
          fi
          
          echo "📦 IPA encontrado: $IPA_FILE"
          ls -lh "$IPA_FILE"
          
          echo "☁️ Autenticando con Azure..."
          az login --service-principal \
            -u "$AZURE_CLIENT_ID" \
            -p "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

          TIMESTAMP=$(date +%Y%m%d%H%M)
          BLOB_NAME="tongi-ios-${TIMESTAMP}.ipa"

          echo "⬆️ Subiendo IPA a Azure Blob Storage..."
          az storage blob upload \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --container-name "$AZURE_CONTAINER" \
            --name "$BLOB_NAME" \
            --file "$IPA_FILE" \
            --auth-mode login

          echo "✅ IPA subido correctamente a Azure!"
          echo "📍 Nombre del archivo: $BLOB_NAME"
          echo "📍 URL: https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_CONTAINER}/${BLOB_NAME}"

    artifacts:
      - frontend/build/ios/ipa/*.ipa