workflows:
  ios-test:
    name: "iOS Build Test"
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        AZURE_STORAGE_ACCOUNT: "tongiapks"
        AZURE_CONTAINER: "apk"
      groups:
        - azure

    triggering:
      events:
        - push

    scripts:
      - name: Clean
        script: |
          cd frontend
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Flutter pub get
        script: |
          cd frontend
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios
          pod install

      - name: Build IPA (sin firmar)
        script: |
          cd frontend
          set -e  # Detener si hay error
          flutter build ipa --release --no-codesign
          
          # Verificar que el build fue exitoso
          if [ ! -d "build/ios/iphoneos" ]; then
            echo "❌ Error: No se generó el build de iOS"
            exit 1
          fi

      - name: Create IPA manually
        script: |
          cd frontend
          
          # Crear directorio para el IPA
          mkdir -p build/ios/ipa
          
          # Crear el IPA desde el .app
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa ../ipa/
          cd ../../../
          
          echo "✅ IPA creado manualmente"
          ls -lh build/ios/ipa/

      - name: Install Azure CLI
        script: |
          brew update
          brew install azure-cli

      - name: Upload IPA to Azure Blob Storage
        script: |
          cd frontend
          
          # Verificar que el IPA existe
          IPA_FILE=$(find build/ios/ipa -name "*.ipa" | head -n 1)
          
          if [ -z "$IPA_FILE" ] || [ ! -f "$IPA_FILE" ]; then
            echo "❌ Error: No se encontró el archivo IPA"
            ls -R build/ios/
            exit 1
          fi
          
          echo "📦 IPA encontrado: $IPA_FILE"
          ls -lh "$IPA_FILE"
          
          echo "☁️ Autenticando con Azure..."
          az login --service-principal \
            -u "$AZURE_CLIENT_ID" \
            -p "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

          TIMESTAMP=$(date +%Y%m%d%H%M)

          echo "⬆️ Subiendo IPA a Azure Blob Storage..."
          az storage blob upload \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --container-name "$AZURE_CONTAINER" \
            --name "tongi-ios-${TIMESTAMP}.ipa" \
            --file "$IPA_FILE" \
            --auth-mode login

          echo "✅ IPA subido correctamente a Azure!"
          echo "📍 URL: https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_CONTAINER}/tongi-ios-${TIMESTAMP}.ipa"

    artifacts:
      - frontend/build/ios/ipa/*.ipa