workflows:
  ios-test:
    name: "iOS Build Test"
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        AZURE_STORAGE_ACCOUNT: "tongiapks"
        AZURE_CONTAINER: "apk"
      groups:
        - azure

    triggering:
      events:
        - push

    scripts:
      - name: Clean
        script: |
          cd frontend
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Flutter pub get
        script: |
          cd frontend
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios
          pod install

      - name: Build IPA (sin firmar)
        script: |
          cd frontend
          flutter build ipa --release --no-codesign

      - name: Install Azure CLI
        script: |
          brew update
          brew install azure-cli

      - name: Upload IPA to Azure Blob Storage
        script: |
          echo "☁️ Autenticando con Azure..."
          az login --service-principal \
            -u "$AZURE_CLIENT_ID" \
            -p "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

          TIMESTAMP=$(date +%Y%m%d%H%M)
          IPA_FILE=$(find frontend/build/ios/ipa -name "*.ipa" | head -n 1)

          echo "⬆️ Subiendo IPA a Azure Blob Storage..."
          az storage blob upload \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --container-name "$AZURE_CONTAINER" \
            --name "tongi-ios-${TIMESTAMP}.ipa" \
            --file "$IPA_FILE" \
            --auth-mode login

          echo "✅ IPA subido correctamente a Azure!"

    artifacts:
      - frontend/build/ios/ipa/*.ipa