workflows:
  ios-test:
    name: "iOS Build Test"
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    triggering:
      events:
        - push

    scripts:
      - name: Clean
        script: |
          cd frontend
          flutter clean

      - name: Flutter pub get
        script: |
          cd frontend
          flutter pub get

      - name: Build IPA (sin firmar)
        script: |
          cd frontend
          flutter build ipa --release --no-codesign

    artifacts:
      - frontend/build/ios/ipa/*.ipa
