class Language {
  final String label;
  final String code;

  const Language({required this.label, required this.code});
}

const Map<String, String> tongiLanguages = {
  "Afrikáans": "af",
  "Árabe": "ar",
  "Bielorruso": "be",
  "Búlgaro": "bg",
  "Bengalí": "bn",
  "Catalán": "ca",
  "Checo": "cs",
  "Galés": "cy",
  "Danés": "da",
  "Alemán": "de",
  "Griego": "el",
  "Inglés": "en",
  "Esperanto": "eo",
  "Español": "es",
  "Estonio": "et",
  "Persa": "fa",
  "Finés": "fi",
  "Francés": "fr",
  "Irlandés": "ga",
  "Galego": "gl",
  "Guyaratí": "gu",
  "Hebreo": "he",
  "Hindi": "hi",
  "Croata": "hr",
  "Haitiano": "ht",
  "Húngaro": "hu",
  "Indonesio": "id",
  "Islandés": "is",
  "Italiano": "it",
  "Japonés": "ja",
  "Georgiano": "ka",
  "Canarés": "kn",
  "Coreano": "ko",
  "Lituano": "lt",
  "Letón": "lv",
  "Macedonio": "mk",
  "Maratí": "mr",
  "Malay": "ms",
  "Maltés": "mt",
  "Neerlandés": "nl",
  "Noruego": "no",
  "Polaco": "pl",
  "Portugués": "pt",
  "Rumano": "ro",
  "Ruso": "ru",
  "Eslovaco": "sk",
  "Esloveno": "sl",
  "Albanés": "sq",
  "Sueco": "sv",
  "Suajili": "sw",
  "Tamil": "ta",
  "Telugu": "te",
  "Tailandés": "th",
  "Tagalo": "tl",
  "Turco": "tr",
  "Ucraniano": "uk",
  "Urdu": "ur",
  "Vietnamita": "vi",
  "Chino": "zh",
};

const List<Language> availableLanguages = [
  Language(label: "Español", code: "es"),
  Language(label: "Inglés", code: "en"),
  Language(label: "Alemán", code: "de"),
  Language(label: "Italiano", code: "it"),
  Language(label: "Japones", code: "jp"),
];
