class Language {
  final String label;
  final String code;

  const Language({required this.label, required this.code});
}

const Map<String, String> tongiLanguages = {
  "es": "Español",
  "en": "Inglés",
  "fr": "Francés",
  "de": "Alemán",
  "it": "Italiano",
  "pt": "Portugués",
  "zh-Hans": "Chino Simplificado",
  "zh-Hant": "Chino Tradicional",
  "ja": "Japonés",
  "ko": "Coreano",
  "ar": "Árabe",
  "ru": "Ruso",
  "hi": "Hindi",
};

const Map<String, String> localLanguages = {
  "af": "Afrikáans",
  "ar": "Árabe",
  "be": "Bielorruso",
  "bg": "Búlgaro",
  "bn": "Bengalí",
  "ca": "Catalán",
  "cs": "Checo",
  "cy": "Galés",
  "da": "Danés",
  "de": "Alemán",
  "el": "Griego",
  "en": "Inglés",
  "eo": "Esperanto",
  "es": "Español",
  "et": "Estonio",
  "fa": "Persa",
  "fi": "Finés",
  "fr": "Francés",
  "ga": "Irlandés",
  "gl": "Galego",
  "gu": "Guyaratí",
  "he": "Hebreo",
  "hi": "Hindi",
  "hr": "Croata",
  "ht": "Haitiano",
  "hu": "Húngaro",
  "id": "Indonesio",
  "is": "Islandés",
  "it": "Italiano",
  "ja": "Japonés",
  "ka": "Georgiano",
  "kn": "Canarés",
  "ko": "Coreano",
  "lt": "Lituano",
  "lv": "Letón",
  "mk": "Macedonio",
  "mr": "Maratí",
  "ms": "Malay",
  "mt": "Maltés",
  "nl": "Neerlandés",
  "no": "Noruego",
  "pl": "Polaco",
  "pt": "Portugués",
  "ro": "Rumano",
  "ru": "Ruso",
  "sk": "Eslovaco",
  "sl": "Esloveno",
  "sq": "Albanés",
  "sv": "Sueco",
  "sw": "Suajili",
  "ta": "Tamil",
  "te": "Telugu",
  "th": "Tailandés",
  "tl": "Tagalo",
  "tr": "Turco",
  "uk": "Ucraniano",
  "ur": "Urdu",
  "vi": "Vietnamita",
  "zh": "Chino",
};

const List<Language> availableLanguages = [
  Language(label: "Español", code: "es"),
  Language(label: "Inglés", code: "en"),
  Language(label: "Francés", code: "fr"),
  Language(label: "Alemán", code: "de"),
  Language(label: "Italiano", code: "it"),
  Language(label: "Portugués", code: "pt"),
  Language(label: "Chino Simplificado", code: "zh-Hans"),
  Language(label: "Chino Tradicional", code: "zh-Hant"),
  Language(label: "Japonés", code: "ja"),
  Language(label: "Coreano", code: "ko"),
  Language(label: "Árabe", code: "ar"),
  Language(label: "Ruso", code: "ru"),
  Language(label: "Hindi", code: "hi"),
];
