class Language {
  final String label;
  final String code;

  const Language({required this.label, required this.code});
}

const List<Language> availableLanguages = [
  Language(label: "Español", code: "es"),
  Language(label: "Afrikaans", code: "af"),
  Language(label: "Amárico", code: "am"),
  Language(label: "Árabe", code: "ar"),
  Language(label: "Árabe", code: "ar-Latn"),
  Language(label: "Azerí", code: "az"),
  Language(label: "Bielorruso", code: "be"),
  Language(label: "Búlgaro", code: "bg"),
  Language(label: "Búlgaro", code: "bg latino"),
  Language(label: "Bengalí", code: "bn"),
  Language(label: "Bosnio", code: "bs"),
  Language(label: "Catalán", code: "ca"),
  Language(label: "Cebuano", code: "ceb"),
  Language(label: "Corso", code: "co"),
  Language(label: "Checo", code: "cs"),
  Language(label: "Galés", code: "cy"),
  Language(label: "Danés", code: "da"),
  Language(label: "Alemán", code: "de"),
  Language(label: "Griego", code: "el"),
  Language(label: "Griego", code: "el-Latn"),
  Language(label: "Inglés", code: "en"),
  Language(label: "Esperanto", code: "eo"),
  Language(label: "Español", code: "es"),
  Language(label: "Estonio", code: "et"),
  Language(label: "Vasco", code: "eu"),
  Language(label: "Persa", code: "fa"),
  Language(label: "Finés", code: "fi"),
  Language(label: "Filipino", code: "fil"),
  Language(label: "Franc", code: "fr"),
  Language(label: "Frisón occidental", code: "fy"),
  Language(label: "Irlandés", code: "ga"),
  Language(label: "Gaélico esc", code: "gd"),
  Language(label: "Galego", code: "gl"),
  Language(label: "Guyaratí", code: "gu"),
  Language(label: "Hausa", code: "ha"),
  Language(label: "Hawaiana", code: "haw"),
  Language(label: "Hebreo", code: "he"),
  Language(label: "Hindi", code: "hi"),
  Language(label: "Hindi", code: "hi-latn"),
  Language(label: "Hmong", code: "hm"),
  Language(label: "Croata", code: "h"),
  Language(label: "Haitiano", code: "ht"),
  Language(label: "Húngaro", code: "hu"),
  Language(label: "Armenio", code: "hy"),
  Language(label: "Indonesio", code: "id"),
  Language(label: "Igbo", code: "ig"),
  Language(label: "Islandés", code: "is"),
  Language(label: "Italiano", code: "it"),
  Language(label: "Japonés", code: "ja"),
  Language(label: "Japonés", code: "Ja-Latn"),
  Language(label: "Javanés", code: "jv"),
  Language(label: "Georgiano", code: "ka"),
  Language(label: "Kazajo", code: "kk"),
  Language(label: "Jemer", code: "km"),
  Language(label: "Canarés", code: "kn"),
  Language(label: "Coreano", code: "ko"),
  Language(label: "Kurdo", code: "ku"),
  Language(label: "Kirguís", code: "ky"),
  Language(label: "Latín", code: "la"),
  Language(label: "Luxemburgués", code: "lb"),
  Language(label: "Laosiano", code: "lo"),
  Language(label: "Lituano", code: "lt"),
  Language(label: "Letón", code: "lv"),
  Language(label: "Malgache", code: "mg"),
  Language(label: "Maorí", code: "millas"),
  Language(label: "Macedonio", code: "mk"),
  Language(label: "Malabar", code: "ml"),
  Language(label: "Mongol", code: "mn"),
  Language(label: "Maratí", code: "mr"),
  Language(label: "Malay", code: "ms"),
  Language(label: "Maltés", code: "mt"),
  Language(label: "Birmano", code: "my"),
  Language(label: "Nepalí", code: "ne"),
  Language(label: "Neerlandés", code: "nl"),
  Language(label: "Noruego", code: "no"),
  Language(label: "Nyanja", code: "ny"),
  Language(label: "Panyabí", code: "pa"),
  Language(label: "Perfeccionar", code: "pl"),
  Language(label: "Pastún", code: "ps"),
  Language(label: "Portugués", code: "pt"),
  Language(label: "Rumano", code: "ro"),
  Language(label: "Ruso", code: "ru"),
  Language(label: "Ruso", code: "rusia"),
  Language(label: "Sindhi", code: "sd"),
  Language(label: "Cingalés", code: "si"),
  Language(label: "Eslovaco", code: "sk"),
  Language(label: "Esloveno", code: "sl"),
  Language(label: "Samoano", code: "sm"),
  Language(label: "Shona", code: "sn"),
  Language(label: "Somalí", code: "so"),
  Language(label: "Albanés", code: "sq"),
  Language(label: "Serbio", code: "sr"),
  Language(label: "Sesotho", code: "st"),
  Language(label: "Sundanés", code: "su"),
  Language(label: "Sueco", code: "sv"),
  Language(label: "Suajili", code: "sw"),
  Language(label: "Tamil", code: "ta"),
  Language(label: "Telugu", code: "te"),
  Language(label: "Tajik", code: "tg"),
  Language(label: "Tailandés", code: "th"),
  Language(label: "Turco", code: "tr"),
  Language(label: "Ucraniano", code: "uk"),
  Language(label: "Urdu", code: "ur"),
  Language(label: "Uzbeco", code: "uz"),
  Language(label: "Vietnamita", code: "vi"),
  Language(label: "Xhosa", code: "xh"),
  Language(label: "Yiddish", code: "yi"),
  Language(label: "Yoruba", code: "oye"),
  Language(label: "Chino", code: "zh"),
  Language(label: "Chino", code: "zh-latn"),
  Language(label: "Zulú", code: "zu")
];
