const Map<String, String> availableLanguages = {
  "Español": "es",
  "Afrikaans": "af",
  "Amárico": "am",
  "Árabe": "ar",
  "Árabe (romanizado)": "ar-Latn",
  "Azerí": "az",
  "Bielorruso": "be",
  "Búlgaro": "bg",
  "Búlgaro (romanizado)": "bg latino",
  "Bengalí": "bn",
  "Bosnio": "bs",
  "Catalán": "ca",
  "Cebuano": "ceb",
  "Corso": "co",
  "Checo": "cs",
  "Galés": "cy",
  "Danés": "da",
  "Alemán": "de",
  "Griego": "el",
  "Griego (romanizado)": "el-Latn",
  "Inglés": "en",
  "Esperanto": "eo",
  "Estonio": "et",
  "Vasco": "eu",
  "Persa": "fa",
  "Finés": "fi",
  "Filipino": "fil",
  "Franc": "fr",
  "Frisón occidental": "fy",
  "Irlandés": "ga",
  "Gaélico esc": "gd",
  "Galego": "gl",
  "Guyaratí": "gu",
  "Hausa": "ha",
  "Hawaiana": "haw",
  "Hebreo": "he",
  "Hindi": "hi",
  "Hindi (romanizado)": "hi-latn",
  "Hmong": "hm",
  "Croata": "h",
  "Haitiano": "ht",
  "Húngaro": "hu",
  "Armenio": "hy",
  "Indonesio": "id",
  "Igbo": "ig",
  "Islandés": "is",
  "Italiano": "it",
  "Japonés": "ja",
  "Japonés (romanizado)": "Ja-Latn",
  "Javanés": "jv",
  "Georgiano": "ka",
  "Kazajo": "kk",
  "Jemer": "km",
  "Canarés": "kn",
  "Coreano": "ko",
  "Kurdo": "ku",
  "Kirguís": "ky",
  "Latín": "la",
  "Luxemburgués": "lb",
  "Laosiano": "lo",
  "Lituano": "lt",
  "Letón": "lv",
  "Malgache": "mg",
  "Maorí": "millas",
  "Macedonio": "mk",
  "Malabar": "ml",
  "Mongol": "mn",
  "Maratí": "mr",
  "Malay": "ms",
  "Maltés": "mt",
  "Birmano": "my",
  "Nepalí": "ne",
  "Neerlandés": "nl",
  "Noruego": "no",
  "Nyanja": "ny",
  "Panyabí": "pa",
  "Polaco": "pl",
  "Pastún": "ps",
  "Portugués": "pt",
  "Rumano": "ro",
  "Ruso": "ru",
  "Ruso (alternativo)": "rusia",
  "Sindhi": "sd",
  "Cingalés": "si",
  "Eslovaco": "sk",
  "Esloveno": "sl",
  "Samoano": "sm",
  "Shona": "sn",
  "Somalí": "so",
  "Albanés": "sq",
  "Serbio": "sr",
  "Sesotho": "st",
  "Sundanés": "su",
  "Sueco": "sv",
  "Suajili": "sw",
  "Tamil": "ta",
  "Telugu": "te",
  "Tajik": "tg",
  "Tailandés": "th",
  "Turco": "tr",
  "Ucraniano": "uk",
  "Urdu": "ur",
  "Uzbeco": "uz",
  "Vietnamita": "vi",
  "Xhosa": "xh",
  "Yiddish": "yi",
  "Yoruba": "oye",
  "Chino": "zh",
  "Chino (romanizado)": "zh-latn",
  "Zulú": "zu",
};
