# ETAPA 1: Construcción de dependencias Python
FROM python:3.11-slim AS python-base

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libasound2 \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar y instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el proyecto
COPY . .

# Exponer puerto que Azure inyectará
EXPOSE 8003

# Gunicorn con UvicornWorker (ASGI) para producción
CMD ["gunicorn", "--bind", "0.0.0.0:8003", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-", "app:app"]

