pipeline {
    agent any
    environment {
        IMAGE_NAME = 'myacr.azurecr.io/server1:latest'
        AZURE_CREDENTIALS = credentials('azure-docker-login')
    }
    stages {
        stage('Build Docker image') {
            steps {
                dir('servers/stt_server') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }
        // stage('Login to Azure') {
        //     steps {
        //         sh 'echo $AZURE_CREDENTIALS_PSW | docker login myacr.azurecr.io -u $AZURE_CREDENTIALS_USR --password-stdin'
        //     }
        // }
        // stage('Push Docker image') {
        //     steps {
        //         sh 'docker push $IMAGE_NAME'
        //     }
        // }
    }
    post {
        success {
            echo "✅ Image for stt_server pushed to Azure successfully!"
        }
        failure {
            echo "❌ Failed to push image for stt_server."
        }
    }
}
